In [1]:
import pandas as pd
import numpy as np

# Loading Kickstarter Data

In [2]:
projects = pd.read_csv('data/ks-projects-201801.csv', encoding='ISO-8859-1')

In [3]:
projects

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00
10,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09 18:19:37,0.00,failed,0,CA,0.00,0.00,2406.39
11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09 06:42:58,12700.00,successful,100,US,12700.00,12700.00,12500.00
12,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02 17:11:50,0.00,failed,0,US,0.00,0.00,5000.00
13,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25,200000.0,2016-02-09 23:01:12,0.00,failed,0,US,0.00,0.00,200000.00
14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05 19:44:18,94175.00,successful,761,GB,57763.78,121857.33,6469.73
15,1000064368,Survival Rings,Design,Design,USD,2015-02-28,2500.0,2015-01-29 02:10:53,664.00,failed,11,US,664.00,664.00,2500.00
16,1000064918,The Beard,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09 22:27:52,395.00,failed,16,US,395.00,395.00,1500.00
17,1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10 21:20:54,789.00,failed,20,US,789.00,789.00,3000.00
18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17,250.0,2012-08-02 14:11:32,250.00,successful,7,US,250.00,250.00,250.00
19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03 17:24:32,1781.00,failed,40,US,1781.00,1781.00,5000.00
20,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25 07:06:11,34268.00,successful,624,US,34268.00,34268.00,20000.00
21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08 01:20:20,1.00,failed,1,AU,0.00,0.81,2026.10
22,1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16 10:10:38,650.00,failed,12,US,650.00,650.00,3500.00
23,1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26 19:17:33,48.00,failed,3,NO,6.18,6.29,65.55
24,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12,175.0,2014-10-23 17:15:50,701.66,successful,66,US,701.66,701.66,175.00
25,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06,10000.0,2010-12-07 23:16:50,15827.00,successful,147,US,15827.00,15827.00,10000.00
26,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06 20:09:06,0.00,failed,0,GB,0.00,0.00,17489.65
27,1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14 18:02:00,48905.00,successful,571,CA,43203.25,42174.03,15313.04
28,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29 16:59:29,112.38,successful,27,GB,167.70,160.60,142.91
29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03 17:11:33,57577.31,successful,840,US,10120.00,57577.31,50000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378631,999832803,MONSTROCARDS- A Creative Drawing Game of Horri...,Playing Cards,Games,USD,2014-10-03,10000.0,2014-09-03 19:53:50,13861.50,successful,413,US,13861.50,13861.50,10000.00
378632,99984851,"""Loreto""",Comedy,Film & Video,USD,2014-06-05,12000.0,2014-05-06 23:50:34,0.00,failed,0,US,0.00,0.00,12000.00
378633,999865831,STATE OF G - Men's Blazer Jacket & Women's Car...,Apparel,Fashion,USD,2014-12-13,25000.0,2014-11-13 17:16:17,11643.00,failed,97,US,11643.00,11643.00,25000.00
378634,999867839,Transcaucasia,Photography,Photography,USD,2011-01-08,4000.0,2010-11-08 02:43:59,3531.00,failed,37,US,3531.00,3531.00,4000.00
378635,99987261,"You're Not Cis, You Just Think You Are: My Enb...",Nonfiction,Publishing,USD,2015-09-24,800.0,2015-08-25 22:37:14,70.00,failed,5,US,70.00,70.00,800.00
378636,999877902,Little Saturday's Debut Album,Country & Folk,Music,CAD,2014-12-17,5000.0,2014-11-17 17:50:12,5435.00,successful,78,CA,4814.88,4686.96,4311.83
378637,999878813,Ways to Look at the Moon,Shorts,Film & Video,USD,2017-10-13,10000.0,2017-08-29 06:57:28,10245.00,successful,123,US,145.00,10245.00,10000.00
378638,999880710,Terminal Uniqueness,Nonfiction,Publishing,USD,2014-08-15,5000.0,2014-07-15 02:10:39,18.00,failed,5,US,18.00,18.00,5000.00
378639,999884445,Superette Tea - Boldly Caffeinated Loose Leaf Tea,Drinks,Food,USD,2015-12-03,5000.0,2015-11-03 13:04:14,5579.00,successful,103,US,5579.00,5579.00,5000.00
378640,999893629,Ciridian Helix (Canceled),Fiction,Publishing,USD,2014-09-11,1000.0,2014-08-08 21:49:31,100.00,canceled,2,US,100.00,100.00,1000.00
378641,99991751,Here is the oasis for the youngest in the world.,Product Design,Design,CHF,2015-09-04,80000.0,2015-07-06 18:00:47,0.00,failed,0,CH,0.00,0.00,82207.27
378642,999929142,ÃPOUVANTAILS : 28mm Figurines de jeux pour KI...,Tabletop Games,Games,EUR,2017-10-31,1000.0,2017-10-04 11:26:44,1246.00,successful,35,FR,66.72,1452.47,1165.70
378643,999931480,Google Glass Shield (Canceled),3D Printing,Technology,USD,2014-05-26,6500.0,2014-05-05 20:22:45,0.00,canceled,0,US,0.00,0.00,6500.00
378644,999934908,The Manual Bar Blade,Product Design,Design,USD,2015-12-15,3500.0,2015-11-23 07:33:14,6169.00,successful,120,US,6169.00,6169.00,3500.00
378645,999941823,The Chronicles of Erinoth - A Graphic Novel,Comics,Comics,GBP,2013-10-10,16000.0,2013-09-10 22:45:26,2738.00,failed,38,GB,4281.15,4374.99,25566.05
378646,999943841,The Dog Coffee Book,Children's Books,Publishing,USD,2013-11-30,950.0,2013-10-18 21:35:04,1732.02,successful,31,US,1732.02,1732.02,950.00
378647,999950812,The Cease is Increase,Nonfiction,Publishing,USD,2012-09-14,4999.0,2012-08-15 17:11:00,980.00,failed,16,US,980.00,980.00,4999.00
378648,999955533,Cards and Chit Network Season 2! (Canceled),Tabletop Games,Games,USD,2016-02-23,500.0,2016-01-24 16:03:27,121.00,canceled,5,US,121.00,121.00,500.00
378649,999963618,Colorado International Activism Film Festival,Narrative Film,Film & Video,USD,2017-04-09,500.0,2017-02-08 02:28:44,135.00,failed,6,US,45.00,135.00,500.00
378650,99996661,Date Seat - Boston iOS App,Apps,Technology,USD,2016-09-05,6000.0,2016-07-29 15:36:29,0.00,failed,0,US,0.00,0.00,6000.00
378651,999969812,AT THE BEACH,Classical Music,Music,CAD,2014-03-22,5000.0,2014-02-20 01:00:16,5501.00,successful,78,CA,5019.92,4983.69,4529.81
378652,999971898,Beach Wrestling Documentary,Documentary,Film & Video,NOK,2015-04-28,20000.0,2015-03-29 21:30:33,21500.00,successful,36,NO,2698.97,2875.83,2675.19
378653,999972264,Islanda,Documentary,Film & Video,USD,2012-03-16,1700.0,2012-02-15 04:31:10,25.00,failed,1,US,25.00,25.00,1700.00
378654,999975836,"Homemade fresh dog food, Cleveland OH",Small Batch,Food,USD,2017-04-19,6500.0,2017-03-20 22:08:22,154.00,failed,4,US,0.00,154.00,6500.00
378655,999976312,Angela's Poetry (Canceled),Poetry,Publishing,CAD,2014-09-20,5500.0,2014-08-06 03:46:07,0.00,canceled,0,CA,0.00,0.00,4949.60
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.00,canceled,1,US,25.00,25.00,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.00,failed,5,US,155.00,155.00,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.00,failed,1,US,20.00,20.00,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.00,failed,6,US,200.00,200.00,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.00,failed,17,US,524.00,524.00,2000.00

In [4]:
projects.shape

(378661, 15)

In [5]:
liveProjects = projects[projects.state.str.startswith('live')]

In [6]:
liveProjects.shape

(2799, 15)

In [7]:
prunedProjects = projects[~(projects.state.str.startswith('canceled') | projects.state.str.startswith('live') | projects.state.str.startswith('suspended'))]

In [8]:
prunedProjects.shape

(335237, 15)

# Getting related data

In [9]:
# maybe try backers, category also
truth_related_cols = ['ID', 'state']
related_cols = ['ID', 'name', 'main_category', 'launched', 'deadline', 'usd_goal_real', 'usd_pledged_real']

In [10]:
# truth = prunedProjects[truth_related_cols]
related_projects = prunedProjects[related_cols]
related_live_projects = liveProjects[related_cols]

In [11]:
related_projects.head()

,ID,name,main_category,launched,deadline,usd_goal_real,usd_pledged_real
0,1000002330,The Songs of Adelaide & Abullah,Publishing,2015-08-11 12:12:28,2015-10-09,1533.95,0.0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Film & Video,2017-09-02 04:43:57,2017-11-01,30000.00,2421.0
2,1000004038,Where is Hank?,Film & Video,2013-01-12 00:20:50,2013-02-26,45000.00,220.0
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,2012-03-17 03:24:11,2012-04-16,5000.00,1.0
5,1000014025,Monarch Espresso Bar,Food,2016-02-26 13:38:27,2016-04-01,50000.00,52375.0

# Pruning Data

In [12]:
# prunedData = related_projects[~(related_projects.deadline.str.startswith('2010')
#                              | related_projects.deadline.str.startswith('2011')
#                              | related_projects.deadline.str.startswith('2012')
#                              | related_projects.deadline.str.startswith('2013')
#                              | related_projects.deadline.str.startswith('2014'))]
prunedData = prunedProjects[related_projects.deadline.str.startswith('2018') | related_projects.deadline.str.startswith('2017')]

In [13]:
prunedData

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05 19:44:18,94175.00,successful,761,GB,57763.78,121857.33,6469.73
21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08 01:20:20,1.00,failed,1,AU,0.00,0.81,2026.10
29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03 17:11:33,57577.31,successful,840,US,10120.00,57577.31,50000.00
43,1000170964,Penny Bingo Playing Card Game fun for the whol...,Tabletop Games,Games,USD,2017-03-27,1500.0,2017-03-02 04:01:43,856.00,failed,25,US,324.00,856.00,1500.00
51,100020143,H2O The Underwater Portraits,People,Photography,USD,2017-10-30,9500.0,2017-09-25 17:17:43,6.00,failed,2,US,5.00,6.00,9500.00
67,1000256230,Shreddit - Privacy on Reddit,Software,Technology,GBP,2017-07-02,2000.0,2017-06-02 12:20:21,0.00,failed,0,GB,0.00,0.00,2579.35
90,1000348690,The Silence of Hollowind - Urban Fantasy RPG,Tabletop Games,Games,EUR,2017-11-23,5000.0,2017-10-24 16:58:01,11238.00,successful,346,IT,5509.51,13347.43,5938.52
106,10004373,Bad Example (A Southern Trailer Park Fairy Tal...,Shorts,Film & Video,USD,2017-05-08,1800.0,2017-04-03 23:25:55,22.00,failed,2,US,7.00,22.00,1800.00
112,1000468345,iRNinja - Control your TV with a simple press ...,Gadgets,Technology,USD,2017-06-14,500.0,2017-05-10 16:00:18,74.00,failed,6,US,261.00,74.00,500.00
116,1000490852,Carriage,Art,Art,USD,2017-12-24,8000.0,2017-11-24 18:06:35,8360.00,successful,121,US,605.00,8360.00,8000.00
117,1000491057,AllThis TV,Comedy,Film & Video,USD,2017-04-09,50000.0,2017-03-10 01:12:32,40.00,failed,3,US,20.00,40.00,50000.00
138,100056789,Four Short Stories and Ten Love Poems,Publishing,Publishing,USD,2017-08-25,3000.0,2017-07-11 17:43:09,3165.00,successful,33,US,225.00,3165.00,3000.00
146,1000598804,Gone In 61 Seconds,Tabletop Games,Games,USD,2017-11-08,1000.0,2017-11-03 13:44:35,875.00,failed,14,US,420.00,875.00,1000.00
149,1000600868,Musical stage (escenario musical),Latin,Music,MXN,2017-04-17,18000.0,2017-03-03 22:34:24,10.00,failed,1,MX,0.00,0.53,955.82
160,100065084,One Man's Opinion Of Moonlight Song Collection,Music,Music,USD,2017-06-29,1450.0,2017-06-14 19:57:18,1647.00,successful,33,US,0.00,1647.00,1450.00
163,1000654409,Echo-Fuel: Make Echo Portable with Universal C...,Hardware,Technology,USD,2017-12-07,50000.0,2017-11-04 19:46:50,4237.00,failed,12,US,4384.00,4237.00,50000.00
196,1000804307,Ropw,Games,Games,USD,2017-09-22,2000.0,2017-08-23 09:59:23,3.69,failed,3,US,0.00,3.69,2000.00
197,1000804742,The Chelsea Chronicle Podcast,Audio,Journalism,GBP,2017-02-24,10000.0,2017-01-25 16:21:21,337.50,failed,15,GB,115.05,423.72,12554.61
198,1000810416,Wildlife Inspired T-Shirts; Help Me To Help Wi...,Apparel,Fashion,GBP,2017-07-31,200.0,2017-07-06 17:49:08,15.00,failed,1,GB,19.40,19.72,262.92
202,1000827890,Throw Over Car Door Dent Protector,Design,Design,USD,2017-03-01,5000.0,2017-02-02 23:49:26,45.00,failed,2,US,0.00,45.00,5000.00
203,1000834930,Strawberry Fields CafÃ© and Patisserie,Food,Food,CAD,2017-01-23,50000.0,2016-12-01 21:16:27,0.00,failed,0,CA,0.00,0.00,38112.66
213,1000916036,Conference Paradigm Shift Meeting #3,Performance Art,Art,EUR,2017-12-13,700.0,2017-10-14 08:25:55,85.00,failed,4,FR,88.86,100.35,826.42
224,1000987760,Emotional Makayla: Mommy's Birthday Gift!,Children's Books,Publishing,USD,2017-02-19,3000.0,2017-01-05 19:10:03,91.00,failed,4,US,20.00,91.00,3000.00
226,1000988864,"Alaska Bug Bites, LLC - Farmers Markets Launch",Vegan,Food,USD,2017-04-01,2000.0,2017-02-22 18:32:07,2164.77,successful,52,US,525.00,2164.77,2000.00
241,1001052357,Spilt Milk,Graphic Novels,Comics,AUD,2017-01-08,18000.0,2016-12-09 04:00:31,832.00,failed,23,AU,375.22,623.55,13490.22
249,1001097057,Help Put Community-Building Art in Austin's Pa...,Public Art,Art,USD,2017-04-13,5000.0,2017-03-08 17:54:13,7259.00,successful,26,US,300.00,7259.00,5000.00
254,1001128468,The McKenzie Project,Photography,Photography,CAD,2017-06-01,500.0,2017-04-17 17:54:33,1845.00,successful,30,CA,153.82,1364.34,369.74
270,1001216413,Road Runner multisport smartphone carrier,Product Design,Design,EUR,2017-03-09,59000.0,2017-01-22 16:53:55,4021.00,failed,50,FR,917.10,4264.68,62575.57
275,1001228129,Adult Colour Debut Album,Rock,Music,USD,2017-06-24,2200.0,2017-05-25 22:27:33,2415.00,successful,52,US,355.00,2415.00,2200.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378471,999041859,Vinegar Album Vinyl Pressing and Tour,Music,Music,GBP,2017-10-20,600.0,2017-09-05 01:56:44,726.00,successful,36,GB,0.00,957.33,791.18
378477,999070526,"Suburban Guerilla Productions, OCCUPY for a do...",Music,Music,USD,2017-01-02,10000.0,2016-12-23 22:10:02,0.00,failed,0,US,0.00,0.00,10000.00
378485,999117679,3G Flux Planner,Calendars,Publishing,USD,2017-11-09,7200.0,2017-10-10 18:06:22,2601.00,failed,71,US,576.00,2601.00,7200.00
378489,999123824,Where Is Zog? - a graphic novel of sci-fi misa...,Webcomics,Comics,CAD,2017-11-10,1600.0,2017-10-11 01:00:01,2110.00,successful,72,CA,339.02,1665.35,1262.83
378494,999151837,Kev Adams / Tim Prow Oldhammer Goblin Miniatures,Tabletop Games,Games,USD,2017-02-24,1100.0,2017-02-08 22:02:49,18361.00,successful,213,US,5030.00,18361.00,1100.00
378501,999182097,"Make 100 / ""Do Something"" Art Prints",Illustration,Art,USD,2017-02-14,1600.0,2017-01-30 22:24:49,4906.00,successful,216,US,751.00,4906.00,1600.00
378503,999191512,El Diario. / The Diary.,Drama,Film & Video,MXN,2017-12-16,19500.0,2017-11-01 01:39:15,0.00,failed,0,MX,0.00,0.00,999.44
378506,999207322,Float: The levitating Hot Air Balloon Light,Product Design,Design,GBP,2017-10-16,10000.0,2017-09-09 00:42:47,5031.00,failed,38,GB,2740.02,6634.05,13186.35
378510,999219863,Sayno Anti-drug Educational Game,Games,Games,USD,2017-09-13,35000.0,2017-08-14 19:19:32,15.00,failed,2,US,0.00,15.00,35000.00
378515,999239419,LoveMyBootBoots A handmade boot company making...,Footwear,Fashion,USD,2017-07-21,15000.0,2017-06-21 10:39:20,545.00,failed,4,US,375.00,545.00,15000.00
378517,99924900,The Space Hobo Bottlecap Divination Board,Conceptual Art,Art,USD,2017-01-16,2500.0,2017-01-01 19:50:39,6636.00,successful,191,US,5090.00,6636.00,2500.00
378521,9992603,NUJU -diseÃ±o en madera/design in wood-,Design,Design,MXN,2017-01-14,100000.0,2016-11-30 23:20:13,120120.00,successful,121,MX,2774.10,5464.72,4549.38
378536,999341311,Vann the Artist Paints A Necklace,Children's Books,Publishing,USD,2017-09-01,4750.0,2017-07-29 00:52:48,5058.00,successful,143,US,764.00,5058.00,4750.00
378540,999357376,Kodiak Leather - Classic Weekender Duffel,Accessories,Fashion,USD,2017-09-08,5000.0,2017-07-25 16:32:20,252311.00,successful,839,US,2700.00,252311.00,5000.00
378544,999387668,How To Create a WordPress Website In 2017,Web,Technology,CAD,2017-09-14,500.0,2017-08-25 20:55:06,311.00,failed,16,CA,127.54,256.24,411.96
378551,999419568,Pinball Road Trip: a photo documentary,Photobooks,Photography,EUR,2017-12-05,25000.0,2017-11-05 14:45:59,10270.00,failed,134,NL,4018.52,12059.09,29355.13
378558,99945714,"A new venture, needs a new wheel.",Printing,Crafts,GBP,2017-08-13,2000.0,2017-07-13 07:49:29,2916.00,successful,60,GB,2237.56,3754.20,2574.90
378559,999462268,"Not My President T-shirt Multilingual Text, Am...",Apparel,Fashion,USD,2017-09-23,20.0,2017-08-29 02:48:25,51.00,successful,3,US,25.00,51.00,20.00
378561,999477658,Cidery Tasting Room Buildout,Spaces,Food,USD,2017-09-09,10000.0,2017-08-25 01:57:15,10746.00,successful,98,US,1710.00,10746.00,10000.00
378566,999494808,Invitation to Debate - Martin Luther's 95 Theses,Classical Music,Music,GBP,2017-10-21,2800.0,2017-09-21 13:12:37,3015.00,successful,62,GB,973.31,3947.63,3666.12
378586,999616201,HAYES Short Film,Shorts,Film & Video,GBP,2017-11-24,6000.0,2017-10-25 22:48:18,0.00,failed,0,GB,0.00,0.00,7996.16
378594,999667180,VARIANT WARS - The Prisoners,Fiction,Publishing,USD,2017-07-07,325.0,2017-06-30 03:51:43,425.00,successful,7,US,425.00,425.00,325.00
378599,999685327,Just be MEan Holiday Cards!,Product Design,Design,USD,2017-11-27,1500.0,2017-11-15 21:51:30,377.00,failed,7,US,56.00,377.00,1500.00
378603,999701844,Eggbeater- An Independant Horror/Comedy Film,Horror,Film & Video,USD,2017-05-22,3000.0,2017-04-22 02:27:41,10.00,failed,1,US,0.00,10.00,3000.00
378611,999753943,Parti Bash Mobile App & Technology,Apps,Technology,USD,2017-01-07,25000.0,2016-11-08 23:40:40,120.00,failed,2,US,70.00,120.00,25000.00
378628,999814706,Pug Life - Inspired by the Pug,Apparel,Fashion,GBP,2017-05-03,5000.0,2017-04-03 01:07:20,0.00,failed,0,GB,0.00,0.00,6469.73
378637,999878813,Ways to Look at the Moon,Shorts,Film & Video,USD,2017-10-13,10000.0,2017-08-29 06:57:28,10245.00,successful,123,US,145.00,10245.00,10000.00
378642,999929142,ÃPOUVANTAILS : 28mm Figurines de jeux pour KI...,Tabletop Games,Games,EUR,2017-10-31,1000.0,2017-10-04 11:26:44,1246.00,successful,35,FR,66.72,1452.47,1165.70
378649,999963618,Colorado International Activism Film Festival,Narrative Film,Film & Video,USD,2017-04-09,500.0,2017-02-08 02:28:44,135.00,failed,6,US,45.00,135.00,500.00
378654,999975836,"Homemade fresh dog food, Cleveland OH",Small Batch,Food,USD,2017-04-19,6500.0,2017-03-20 22:08:22,154.00,failed,4,US,0.00,154.00,6500.00

In [14]:
prunedData = prunedData[prunedData.usd_goal_real > 8000]

In [15]:
prunedData.shape

(18871, 15)

In [16]:
truth = prunedData[truth_related_cols]
live_truth = liveProjects[truth_related_cols]

In [17]:
truth.head()

             ID       state
1    1000003930      failed
29    100011318  successful
51    100020143      failed
117  1000491057      failed
163  1000654409      failed

In [18]:
live_truth.head()

             ID state
40   1000149007  live
183  1000761521  live
458  1002183790  live
537  1002599057  live
544  1002629894  live

# One Hot Encoding

In [19]:
projectsCategory_out = prunedData.drop(['main_category', 'usd_goal_real', 'usd_pledged_real', 'state'], 1).join(projects.main_category.str.get_dummies())
liveProjectsCategory_out = liveProjects.drop(['main_category', 'usd_goal_real', 'usd_pledged_real', 'state'], 1).join(liveProjects.main_category.str.get_dummies())

In [20]:
print(projectsCategory_out.shape)
print(liveProjectsCategory_out.shape)

(18871, 26)
(2799, 26)

In [21]:
projectsCategory_out = projectsCategory_out.reset_index()
liveProjectsCategory_out = liveProjectsCategory_out.reset_index()

In [22]:
projectsCategory_out = projectsCategory_out.drop('index',axis=1).set_index('ID')
liveProjectsCategory_out = liveProjectsCategory_out.drop('index',axis=1).set_index('ID')

In [23]:
projectsCategory_out = projectsCategory_out.groupby(projectsCategory_out.index).sum()
liveProjectsCategory_out = liveProjectsCategory_out.groupby(liveProjectsCategory_out.index).sum()

In [24]:
projectsCategory_out = projectsCategory_out.reset_index()
# projectsCategory_out = projectsCategory_out.drop(['goal', 'pledged', 'backers', 'usd pledged'], axis=1)
# projectsCategory_out = projectsCategory_out.drop(['goal', 'pledged', 'backers'], axis=1)
projectsCategory_out = projectsCategory_out.drop(['pledged', 'backers'], axis=1)
projectsCategory_out.head()

,ID,goal,usd pledged,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater
0,358771,50000.0,26668.01,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,422684,34000.0,1130.00,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,452247,33200.0,343.61,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,640380,18000.0,1490.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,771637,30000.0,13740.00,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [25]:
liveProjectsCategory_out = liveProjectsCategory_out.reset_index()
liveProjectsCategory_out = liveProjectsCategory_out.drop(['pledged', 'backers'], axis=1)
liveProjectsCategory_out.head()

,ID,goal,usd pledged,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater
0,511375,4500.0,0.00,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,571559,2700.0,22.96,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,799352,4000.0,177.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,871453,5000.0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,979704,2223.0,93.00,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

# Turn Ground Truths into Numeric Representation

In [26]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(truth['state'])
LE_truth = le.transform(truth['state'])

In [27]:
LE_truth

array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [28]:
truth = truth.drop('state', 1)

In [29]:
truth['state'] = LE_truth

In [30]:
truth.head()

             ID  state
1    1000003930      0
29    100011318      1
51    100020143      0
117  1000491057      0
163  1000654409      0

In [31]:
le2 = preprocessing.LabelEncoder()
le2.fit(live_truth['state'])
LE2_truth = le2.transform(live_truth['state'])

In [32]:
live_truth = live_truth.drop('state', 1)

In [33]:
live_truth['state'] = LE2_truth

In [34]:
projectsCategory_out = projectsCategory_out.merge(truth, on='ID')

In [35]:
projectsCategory_out.head()

,ID,goal,usd pledged,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater,state
0,358771,50000.0,26668.01,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
1,422684,34000.0,1130.00,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,452247,33200.0,343.61,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,640380,18000.0,1490.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,771637,30000.0,13740.00,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

In [36]:
projectsCategory_out.shape

(18871, 19)

# Normalizing Data

In [37]:
X = projectsCategory_out[['goal', 'usd pledged']]
std_scaler = preprocessing.StandardScaler()

std_scaler.fit(X)

X_std = std_scaler.transform(X)

In [38]:
X_std

array([[-0.03776156,  0.39528522],
       [-0.04447072, -0.08583194],
       [-0.04480618, -0.10064695],
       ...,
       [-0.05369583, -0.10712031],
       [-0.05369583, -0.10712031],
       [-0.05369583, -0.10712031]])

In [39]:
projectsCategory_out['goal'] = X_std[0:,0]
projectsCategory_out['usd pledged'] = X_std[0:,1]

In [40]:
projectsCategory_out.head()

,ID,goal,usd pledged,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater,state
0,358771,-0.037762,0.395285,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
1,422684,-0.044471,-0.085832,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,452247,-0.044806,-0.100647,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,640380,-0.051180,-0.079050,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,771637,-0.046148,0.151731,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

# Dates

In [41]:
strippedLaunch = pd.DataFrame()
strippedLaunch['launched'] = prunedData['launched'].str.split(' ').str[0]

In [42]:
strippedLaunch.head()

       launched
1    2017-09-02
29   2017-04-03
51   2017-09-25
117  2017-03-10
163  2017-11-04

In [43]:
# projectsCategory_out['deadline'] = pd.to_datetime(prunedData['deadline'], format='%Y-%m-%d')
dates = pd.DataFrame()
dates['ID'] = projectsCategory_out['ID']
dates['deadline'] = pd.to_datetime(prunedData['deadline'], format='%Y-%m-%d')
dates['launched'] = pd.to_datetime(strippedLaunch['launched'], format='%Y-%m-%d')

In [44]:
dates.dtypes

ID                   int64
deadline    datetime64[ns]
launched    datetime64[ns]
dtype: object

In [45]:
dates['Days Active'] = dates['deadline'] - dates['launched']

In [46]:
projectsCategory_out['Days Active'] = dates['Days Active']

In [47]:
projectsCategory_out.head()

,ID,goal,usd pledged,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater,state,Days Active
0,358771,-0.037762,0.395285,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,NaT
1,422684,-0.044471,-0.085832,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,60 days
2,452247,-0.044806,-0.100647,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaT
3,640380,-0.051180,-0.079050,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,NaT
4,771637,-0.046148,0.151731,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,NaT

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X = np.array(projectsCategory_out.drop(['ID','state'],axis=1))
y = np.array(projectsCategory_out['state'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [50]:
print(X_train.shape)
print(X_test.shape)

(15096, 18)
(3775, 18)

In [51]:
print(y_train.shape)
print(y_test.shape)

(15096,)
(3775,)

# SVM Algorithm

In [52]:
from sklearn import svm

svm_clf = svm.SVC()
svm_clf.fit(X_train,y_train)


y_predSVM = svm_clf.predict(X_test)

print("test", y_test[:10])
print("pred", y_predSVM[:10])

TypeError: float() argument must be a string or a number, not 'NaTType'

# Logistic Algorithm

In [ ]:
import sklearn.linear_model as linear_model

lr_clf = linear_model.LogisticRegression()
lr_clf.fit(X_train, y_train)

y_predREG = lr_clf.predict(X_test)

#probs = lr_clf.predict_proba(X_test)

print("test", y_test[:10])
print("pred", y_predREG[:10])

# MLP Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(30,30,30), max_iter=1000)
mlp.fit(X_train, y_train)

y_predMLP = mlp.predict(X_test)
print("test", y_test[:10])
print("pred", y_predMLP[:10])

In [ ]:
import sklearn.metrics as metrics

# Computations

###         SVM Computation

In [ ]:
print(metrics.confusion_matrix(y_test,y_predSVM))
print(metrics.precision_score(y_test,y_predSVM, average='weighted'))   # Parameter "average" is requred if not a binary model
print(metrics.recall_score(y_test,y_predSVM, average='weighted'))      # Parameter "average" is requred if not a binary model
print(metrics.f1_score(y_test,y_predSVM, average='weighted'))          # Parameter "average" is requred if not a binary model

### Logistic Computation

In [ ]:
print(metrics.confusion_matrix(y_test,y_predREG))
print(metrics.precision_score(y_test,y_predREG, average='weighted'))   # Parameter "average" is requred if not a binary model
print(metrics.recall_score(y_test,y_predREG, average='weighted'))      # Parameter "average" is requred if not a binary model
print(metrics.f1_score(y_test,y_predREG, average='weighted'))          # Parameter "average" is requred if not a binary model

### MLP Computation

In [ ]:
print(metrics.confusion_matrix(y_test,y_predMLP))
print(metrics.precision_score(y_test,y_predMLP, average='weighted'))   # Parameter "average" is requred if not a binary model
print(metrics.recall_score(y_test,y_predMLP, average='weighted'))      # Parameter "average" is requred if not a binary model
print(metrics.f1_score(y_test,y_predMLP, average='weighted'))          # Parameter "average" is requred if not a binary model

### Messing around with some stuff

In [ ]:
# X = np.array(projectsCategory_out.drop(['ID','state'],axis=1))
# y = np.array(projectsCategory_out['state'])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

X_test = liveProjectsCategory_out.drop(['ID'], axis=1)
y_test = live_truth['state']

In [ ]:
print(X_test.shape)
print(y_test.shape)

In [ ]:
# svm_clf = svm.SVC()
svm_clf.fit(X_train,y_train)


y_predSVM = svm_clf.predict(X_test)

print("test", y_test[:10])
print("pred", y_predSVM[:10])

In [ ]:
# lr_clf = linear_model.LogisticRegression()
lr_clf.fit(X_train, y_train)

y_predREG = lr_clf.predict(X_test)

#probs = lr_clf.predict_proba(X_test)
np.set_printoptions(threshold=np.nan)
print("test", y_test[:10])
print("pred", y_predREG[:2799])

In [ ]:
# mlp = MLPClassifier(hidden_layer_sizes=(30,30,30), max_iter=1000)
mlp.fit(X_train, y_train)

y_predMLP = mlp.predict(X_test)
print("pred", y_predMLP[:2799])